<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
$_productCollection = $block->getLoadedProductCollection();

// Daily deal Helper
$_dailydealhelper =$this->helper('Smartwave\Dailydeals\Helper\Data');

$_portohelper = $this->helper('Smartwave\Porto\Helper\Data');
$_category_config = $_portohelper->getConfig('porto_settings/category');
$_category_grid_config = $_portohelper->getConfig('porto_settings/category_grid');
$_product_label_config = $_portohelper->getConfig('porto_settings/product_label');
$_lazyload = $_portohelper->getConfig('porto_settings/optimization/lazyload');
$product_type = $_category_grid_config['product_type'];

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'category_page_list';
    $hover_image = 'category_page_list-hover';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();
    $column_count = $this->getData("column_count"); 
    if($column_count == null) {
        $column_count = 4;
    }
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $image_width = ($_category_config['ratio_width'])?$_category_config['ratio_width']:300;
    $image_height = ($_category_config['ratio_height'])?$_category_config['ratio_height']:300;
    $aspect_ratio = $_category_config['aspect_ratio'];
    if($aspect_ratio)
        $image_height = $image_width;
?>
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <?php endif ?>
        <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
        <div class="products-grid products-<?php /* @escapeNotVerified */ echo $mode; ?> columns<?php echo $column_count; ?> <?php /* @escapeNotVerified */ echo $mode; ?><?php if($product_type == 2): ?> no-padding divider-line<?php endif; ?><?php if($product_type == 5 || $product_type == 6 || $product_type == 7 || $product_type == 8): ?> no-padding<?php endif; ?><?php if($product_type == 6): ?> divider-line<?php endif; ?>">
            <ol class="products product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info type<?php echo $product_type; ?>" data-container="product-grid">
                        <div class="product photo product-item-photo">
                          <a href="<?php echo $_item->getProductUrl() ?>" tabindex="-1">
                              <?php
                                  if($_category_config['aspect_ratio'])
                                      $productImage = $_imagehelper->init($_item, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                  else
                                      $productImage = $_imagehelper->init($_item, $image)->resize($image_width, $image_height);
                                  $productImageUrl = $productImage->getUrl();
                              ?>
                                  <img class="product-image-photo default_image<?php if(!$_lazyload): ?> porto-lazyload<?php endif;?>" <?php if(!$_lazyload): ?>src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" data-<?php endif; ?>src="<?php echo $productImageUrl; ?>" width="<?php echo $image_width; ?>" height="<?php echo $image_height; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                              <?php if($_category_config['alternative_image']): ?>
                              <?php
                                  if($_category_config['aspect_ratio'])
                                      $productHoverImage = $_imagehelper->init($_item, $hover_image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                  else
                                      $productHoverImage = $_imagehelper->init($_item, $hover_image)->resize($image_width, $image_height);
                                  $productHoverImageUrl = $productHoverImage->getUrl();
                              ?>
                                  <?php if($productImageUrl != str_replace("/thumbnail/","/small_image/",$productHoverImageUrl)): ?>
                                  <img class="product-image-photo hover_image<?php if(!$_lazyload): ?> porto-lazyload<?php endif;?>" <?php if(!$_lazyload): ?>src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" data-<?php endif; ?>src="<?php echo $productHoverImageUrl; ?>" width="<?php echo $image_width; ?>" height="<?php echo $image_height; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                                  <?php endif; ?>
                              <?php endif; ?>
                          </a>
                          <?php
                              $product_label = "";
                              if($_product_label_config['sale_label']) {
                                  if ($percentage = $_portohelper->getPercentage($_item)) {
                                      if($_product_label_config['sale_label_percent']) {
                                          $product_label .= '<div class="product-label sale-label">'.$percentage.'%'.'</div>';
                                      } else {
                                          $product_label .= '<div class="product-label sale-label">'.$_product_label_config['sale_label_text'].'</div>';
                                      }
                                  }
                              }
                              if($_product_label_config['new_label']) {
                                  $now = date("Y-m-d");
                                  $newsFrom= substr($_item->getData('news_from_date')?$_item->getData('news_from_date'):'',0,10);
                                  $newsTo=  substr($_item->getData('news_to_date')?$_item->getData('news_to_date'):'',0,10);

                                  if ($newsTo != '' || $newsFrom != ''){
                                      if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)) {
                                          $product_label .= '<div class="product-label new-label">'.$_product_label_config['new_label_text'].'</div>';
                                      }
                                  }
                              }
                              if($product_label)
                                  echo '<div class="product-labels">'.$product_label.'</div>';
                          ?>
                          
                        </div>
                        <div class="product details product-item-details">
                          <?php
                              $_productNameStripped = $block->stripTags($_item->getName(), null, true);
                          ?>
                          <strong class="product name product-item-name">
                              <a class="product-item-link"
                                 href="<?php echo $_item->getProductUrl() ?>">
                                  <?php echo $_helper->productAttribute($_item, $_item->getName(), 'name'); ?>
                              </a>
                          </strong>

                        </div>
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
        <?php echo $block->getPagerHtml() ?>
<?php endif;?>
