<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Form $block */
//phpcs:disable Generic.Files.LineLength
?>
<?php
echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('pdp_block')->toHtml();
?>
<div class="row singleProductRatingReview">
    <div class="col-md-8">
        <h2 class="singleReviewHeading">Ratings & Reviews</h2>
    </div>
    <div class="col-md-4">
        <button class="write_a_review">Write A Review</button>
    </div>
    <div class="col-md-12 singleReviewForm" style="display:none;">
        		<div class="block review-add">
<?php if ($block->getAllowWriteReviewFlag()):?>
<form action="<?= $block->escapeUrl($block->getAction()) ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getChildHtml('form_fields_before') ?>
    <fieldset class="fieldset review-fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <legend class="legend review-legend"><span><?= $block->escapeHtml(__("You're reviewing:")) ?></span><strong><?= $block->escapeHtml($block->getProductInfo()->getName()) ?></strong></legend><br />
        <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
        <span id="input-message-box"></span>
        <fieldset class="field required review-field-ratings">
            <legend class="label"><span><?= $block->escapeHtml(__('Your Rating')) ?></span></legend><br/>
            <div class="control">
                <div class="nested" id="product-review-table">
                    <?php foreach ($block->getRatings() as $_rating): ?>
                        <div class="field choice review-field-rating">
                            <label class="label" id="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?= $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                            <div class="control review-control-vote">
                            <?php $options = $_rating->getOptions();?>
                            <?php $iterator = 1; foreach ($options as $_option): ?>
                                <input
                                    type="radio"
                                    name="ratings[<?= $block->escapeHtmlAttr($_rating->getId()) ?>]"
                                    id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
                                    value="<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                                    class="radio"
                                    data-validate="{'rating-required':true}"
                                    aria-labelledby="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label <?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label" />
                                <label
                                    class="rating-<?= $block->escapeHtmlAttr($iterator) ?>"
                                    for="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>"
                                    title="<?= $block->escapeHtmlAttr(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?>"
                                    id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label">
                                    <span><?= $block->escapeHtml(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?></span>
                                </label>
                                <?php $iterator++; ?>
                            <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
            </div>
        </fieldset>
    <?php endif ?>
        <div class="field review-field-nickname required">
            <label for="nickname_field" class="label"><span><?= $block->escapeHtml(__('Nickname')) ?></span></label>
            <div class="control">
                <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
            </div>
        </div>
        <div class="field review-field-summary required">
            <label for="summary_field" class="label"><span><?= $block->escapeHtml(__('Summary')) ?></span></label>
            <div class="control">
                <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
            </div>
        </div>
        <div class="field review-field-text required">
            <label for="review_field" class="label"><span><?= $block->escapeHtml(__('Review')) ?></span></label>
            <div class="control">
                <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar review-form-actions">
        <div class="primary actions-primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit Review')) ?></span></button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {},
        "Magento_Review/js/validate-review": {},
        "Magento_Review/js/submit-review": {}
    }
}
</script>
<?php else: ?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?= $block->escapeHtml(__('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
        </div>
    </div>
<?php endif ?>
</div>
</div>
</div>
<div class="col-md-12 singlePostedReview">
<?php
$product_id =$block->getProductInfo()->getId();
$sku =$block->getProductInfo()->getSku();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$review = $objectManager->create('\Magento\Review\Block\Product\View\ListView');
$_items = $review->getReviewsCollection()->getItems();

$format = $review->getDateFormat() ?: \IntlDateFormatter::SHORT;
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();

?>

<?php if (count($_items)): ?>
    <div class="block review-list" id="customer-reviews">
        <div class="block-content">
            <ol class="items review-items">
                <?php foreach ($_items as $_review): ?>
                    <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                        
                        <div class="review-content-container">
                           
                            <?php
                            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                            $product = $objectManager->create("Magento\Catalog\Model\Product")->loadByAttribute('sku', $sku); //use load($producID)
                            $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
                            $currentStoreId = $storeManager->getStore()->getId();
                            $reviewFactory = $objectManager->create('Magento\Review\Model\Review');
                            $reviewFactory->getEntitySummary($product, $currentStoreId);    
                            $ratingSummary = $product->getRatingSummary()->getRatingSummary();
                            $_reviewCount = $product->getRatingSummary()->getReviewsCount();
                            $review = $objectManager->get("Magento\Review\Model\ResourceModel\Review\CollectionFactory");
                            $collection = $review->create()->addStoreFilter($currentStoreId)->addStatusFilter(\Magento\Review\Model\Review::STATUS_APPROVED)->addEntityFilter('product',$product->getId())->setDateOrder();
                            ?>
                            <?php if($ratingSummary){ ?>
                            <div class="reviews-actions">
                                <?php echo __($_reviewCount)."Reviews"; ?>
                            </div> 
                               
                            <div class="product-reviews-summary short">
                                <div class="rating-summary">
                                    <div title="<?php echo (int)$ratingSummary; ?>%" class="rating-result">
                                        <span style="width:<?php echo (int)$ratingSummary; ?>%"><span><?php echo (int)$ratingSummary; ?>%</span></span>
                                    </div>
                                </div>
                            </div>
                            <?php } ?>
                            <div class="review-title" itemprop="name">
                                <?php echo $_review->getTitle(); ?>
                            </div>
                            <div class="review-content" itemprop="description">
                                <?php echo $_review->getDetail(); ?>
                            </div>
                            <div class="review-details">
                                <p class="review-author">
                                    <span class="review-details-label">
                                        <?= $escaper->escapeHtml(__('Review by')) ?>
                                    </span>
                                    <strong class="review-details-value" itemprop="author">
                                        <?php echo $_review->getNickname(); ?>
                                    </strong>
                                </p>
                                <p class="review-date">
                                    <span class="review-details-label">
                                        <?= $escaper->escapeHtml(__('Posted on')) ?>
                                    </span>
                                    <time class="review-details-value" itemprop="datePublished">
                                        <?php echo $_review->getCreatedAt(); ?>
                                    </time>
                                </p>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>
</div>
<script>
	require(['jquery', 'jquery/ui'], function($){
	  jQuery(document).ready( function() {
	    jQuery(".write_a_review").click(function(){
		    jQuery(".singleReviewForm").toggle();
		  });
	  });
	});
</script>