<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Contact\Block\ContactForm $block */
?>
 
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <h2 class="size-30" style="font-family:Marcellus; font-weight:500; font-size:40px; padding-top:45px;"><span><?= $block->escapeHtml(__('CONTACT INFORMATION')) ?></span></h2>
        <div class="row gx-5 field">
			<div class="field name required">
				<div class="control">
					<input name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name*')) ?>" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('name') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>" class="input-text" type="text" 
					data-validate="{required:true}" placeholder="<?= $block->escapeHtml(__('Name*')) ?>"/>
				</div>
			</div>
			<div class="field email required">
				<div class="control">
					<input name="email" id="email" 
					title="<?= $block->escapeHtmlAttr(__('Email*')) ?>"
value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('email') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" placeholder="<?= $block->escapeHtml(__('E-Mail*')) ?>"/>
				</div>
			</div>
		</div>
        <div class="field telephone">
            <div class="control">
                <input name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" 
		value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('telephone')) ?>" class="input-text" type="text" 
		placeholder="<?= $block->escapeHtml(__('Telephone')) ?>"/>
            </div>
        </div>
        <div class="field comment required">
            <div class="control">
                <textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Comment*')) ?>" 
		placeholder="<?= $block->escapeHtml(__('Comment*')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary"  style="float:right;">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button  type="submit" title="<?= $block->escapeHtmlAttr(__('SUBMIT')) ?>" class="action submit primary" 
	    style="border-radius: 0px !important;
    padding: 10px 120px;
    font-size: 20px;
    text-transform: uppercase; font-family: Marcellus;
    font-weight: 500; background: #78a79d; border: 1px solid #78a79d;">
                <span><?= $block->escapeHtml(__('SUBMIT')) ?></span>
            </button>
        </div> 
    </div>
</form>
